name: opa_api_authz_dart
description: OPA API Authorization Example in Dart
version: 0.0.1
homepage: https://www.github.com/adaptant-labs/opa-api-authz-dart
repository: https://www.github.com/adaptant-labs/opa-api-authz-dart
issue_tracker: https://github.com/adaptant-labs/opa-api-authz-dart/issues
authors:
- Paul Mundt <paul.mundt@adaptant.io>
- Adaptant Labs <labs@adaptant.io>

environment:
  sdk: '>=2.5.0 <3.0.0'

dependencies:
  http: ^0.12.0+2
  args: ^1.5.2
  glob: ^1.1.7
  path: ^1.6.4

executables:
  opa-api-service: server